### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Tom-NL** [DreanorGTA5Mods/StationaryRadar#19]
Hello can you help me whit: Error loading script server.lua in resource stationaryradar: server.lua:1: attempt to call a nil value (global 'require')

stack traceback:

	server.lua:1: in main chunk

**Comment by dreanor** [comment]
Hey, it could be that you are missing the MySQL.lua and .dll file. I haven't maintained or even finished the mod, I could imagine that after these 2 years a lot has changed for fivem that could have broken things.
